// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Filtertest2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void filtertest2() {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.cssSelector("*[data-test=\"category-01HVSQ0KNPH0MKWDM1RKDNK6F3\"]")).click();
    driver.findElement(By.cssSelector(".checkbox:nth-child(15) .checkbox:nth-child(1) > label")).click();
    driver.findElement(By.cssSelector(".checkbox:nth-child(15) .checkbox:nth-child(2) > label")).click();
    driver.findElement(By.cssSelector(".checkbox:nth-child(15) .checkbox:nth-child(3) > label")).click();
    driver.findElement(By.cssSelector(".checkbox:nth-child(15) .checkbox:nth-child(4) > label")).click();
    driver.findElement(By.cssSelector(".checkbox:nth-child(15) .checkbox:nth-child(5) > label")).click();
    driver.close();
  }
}
