package org.example.Homepage;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;
public class TestRedirects {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.get("https://practicesoftwaretesting.com/");
        driver.manage().window().setSize(new Dimension(697, 723));
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testhomepageicon() {
        driver.findElement(By.id("Layer_1")).click();
        String currentUrl = driver.getCurrentUrl();
        assertEquals("https://practicesoftwaretesting.com/#/", currentUrl);
    }

    @Test
    public void testNavbarHomeLink() {
        driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
        driver.findElement(By.cssSelector("*[data-test=\"nav-home\"]")).click();
        String currentUrl = driver.getCurrentUrl();
        assertEquals("https://practicesoftwaretesting.com/#", currentUrl);
    }


    @Test
    public void testNavbarCategories() {
        driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
        driver.findElement(By.cssSelector("*[data-test=\"nav-categories\"]")).click();
        WebElement categoriesList = driver.findElement(By.cssSelector(".dropdown-menu"));
        assertTrue(categoriesList.isDisplayed());
    }

    @Test
    public void testNavbarContact() {
        driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"nav-contact\"]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector("*[data-test=\"nav-contact\"]")).click();

        String currentUrl = driver.getCurrentUrl();
        assertEquals("https://practicesoftwaretesting.com/#/contact", currentUrl);
    }

    @Test
    public void testNavbarLogin() {
        driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"nav-contact\"]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector("*[data-test=\"nav-sign-in\"]")).click();
        WebDriverWait wait=new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.urlMatches(".*/#/auth/login"));

        String currentUrl = driver.getCurrentUrl();
        assertEquals("https://practicesoftwaretesting.com/#/auth/login", currentUrl);
    }

    @Test
    public void testNavbarDropdownHandTools() {
        driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        WebElement categoriesDropdown = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("*[data-test=\"nav-categories\"]")));
        categoriesDropdown.click();
        WebElement handToolsLink = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("*[data-test=\"nav-hand-tools\"]")));
        handToolsLink.click();
        wait.until(ExpectedConditions.urlMatches(".*/#/category/hand-tools"));

        String currentUrl = driver.getCurrentUrl();
        assertEquals("https://practicesoftwaretesting.com/#/category/hand-tools", currentUrl);
    }

    @Test
    public void testNavbarDropdownPowerTools() {
        driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        WebElement categoriesDropdown = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("*[data-test=\"nav-categories\"]")));
        categoriesDropdown.click();
        WebElement handToolsLink = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("*[data-test=\"nav-power-tools\"]")));
        handToolsLink.click();
        wait.until(ExpectedConditions.urlMatches(".*/#/category/power-tools"));

        String currentUrl = driver.getCurrentUrl();
        assertEquals("https://practicesoftwaretesting.com/#/category/power-tools", currentUrl);
    }

    @Test
    public void testNavbarDropdownOther() {
        driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        WebElement categoriesDropdown = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("*[data-test=\"nav-categories\"]")));
        categoriesDropdown.click();
        WebElement handToolsLink = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("*[data-test=\"nav-other\"]")));
        handToolsLink.click();
        wait.until(ExpectedConditions.urlMatches(".*/#/category/other"));

        String currentUrl = driver.getCurrentUrl();
        assertEquals("https://practicesoftwaretesting.com/#/category/other", currentUrl);
    }

    @Test
    public void testNavbarDropdownSpecialTools() {
        driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        WebElement categoriesDropdown = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("*[data-test=\"nav-categories\"]")));
        categoriesDropdown.click();
        WebElement handToolsLink = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("*[data-test=\"nav-special-tools\"]")));
        handToolsLink.click();
        wait.until(ExpectedConditions.urlMatches(".*/#/category/special-tools"));

        String currentUrl = driver.getCurrentUrl();
        assertEquals("https://practicesoftwaretesting.com/#/category/special-tools", currentUrl);
    }

    @Test
    public void testNavbarDropdownRentals() {
        driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        WebElement categoriesDropdown = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("*[data-test=\"nav-categories\"]")));
        categoriesDropdown.click();
        WebElement handToolsLink = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("*[data-test=\"nav-rentals\"]")));
        handToolsLink.click();
        wait.until(ExpectedConditions.urlMatches(".*/#/rentals"));

        String currentUrl = driver.getCurrentUrl();
        assertEquals("https://practicesoftwaretesting.com/#/rentals", currentUrl);
    }
}

