// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test homepage icon', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test homepage icon', async function() {
    await driver.get("https://practicesoftwaretesting.com/")
    await driver.manage().window().setRect({ width: 697, height: 723 })
    await driver.findElement(By.css(".st3:nth-child(5)")).click()
    await driver.close()
  })
})
